kind: ResourceQuota
apiVersion: v1
metadata:
  name: op1st-gitops
  namespace: op1st-gitops
spec:
  hard:
    limits.cpu: 4000m
    limits.memory: 8Gi
    requests.cpu: 2500m
    requests.memory: 4Gi
